### ISSUE TITLE
Remove button can be clicked without hovering over

### ISSUE THREAD

**Issue by hiepcan** [PlayFab/UnityEditorExtensions#20]
<img width="235" alt="remove" src="https://cloud.githubusercontent.com/assets/19914806/17950802/68a5ef52-6a12-11e6-883e-7b025d85fcd4.png">

The box for remove is bigger than the text itself so when you hover the mouse around it you can still click it

**Comment by zac-playfab** [comment]
There is a confirm prompt prior to taking major actions like this. This is working by design.
