### ISSUE TITLE
Saving settings in EdEx changes ProductionEnvironmentUrl to ".playfabapi.com"

### ISSUE THREAD

**Issue by Mnaukal** [PlayFab/UnityEditorExtensions#32]
When I click on save button in the Editor Extention windows, _ProductionEnvironmentUrl_ in _PlayFabSharedSettings_ changes  to _".playfabapi.com"_, which leads to error on device (_Unable to resolve host ".playfabapi.com"_)

**Comment by zac-playfab** [comment]
Do you also have a title id set? The production environment should be .playfabapi.com. The SDK combines the title id and environment like this {TITLE_ID}{PROD_ENV}, resulting in something like xxxx.playfabapi.com. 

Typically this error message occurs when the title id has not been set.

**Comment by Mnaukal** [comment]
**Sorry, my fault.** I didn't notice that upgrading SDK deleted my _TitleId_ from _PlayFabSharedSettings_. And in the next build after clicking on Save button in the EdEx I thought it was due to the wrong _ProductionEnvironmentUrl_, so I changed it to "_xxxx.playfabapi.com_" and then I got error message "_The URL for this request is not valid for this title. The correct API endpoint is ..._". Maybe you could also show the wrong url in this error message.

**Comment by zac-playfab** [comment]
Yeah if you are using the editor extensions for future SDK upgrades, it should preserve you settings in EditorPrefs while the new SDK is installed, and apply the settings back to the PlayFabSharedSettings ScriptableObject.

I am glad you got working, let us know if you have any other questions!

-Zac
