### ISSUE TITLE
GUI unresponsive

### ISSUE THREAD

**Issue by ParagonFable** [PlayFab/UnityEditorExtensions#35]
Upon installing the package I logged into my Playfab account, it seems to have downloaded the SDK then asked me to setup the title id, after which it's been stuck in some kind of request loop with an orange bar animating across the screen. I can't click on anything else. Exiting unity and re-launching doesn't fix it. Deleting the package files and re-importing doesn't fix it either, upon re importing it opens and is stuck in the exact same loop with without me interacting with anything. 

![image](https://cloud.githubusercontent.com/assets/2350256/18311638/b5be2b38-7548-11e6-84b2-63f7fb89f012.png)

**Comment by zac-playfab** [comment]
Hey ParagonFable,
I have not seen this issue occur. If you can, here are a few things to check.

1. What version of Unity are you using?
2. What OS are you using (make and version)?
2. Do you have any errors in your project that would be prohibiting Unity from recompiling all of the assets?
3. Were there any other form of errors or information you can provide?

Apologies for this issue. I will try and get you a new build as soon as I can.

Thanks,
Zac

**Comment by ParagonFable** [comment]
No need to apologise, it's a beta. Happy to help finding a repo for you.

1) Unity 5.4.0
2) Windows 10 pro (64 bit) Version 1511 build 10586.545
3) An existing project. Did not have existing SDK (this was my first time using Playfab). 
4) Nothing that stands out - I get an ambigious "Unable to parse YMAL file" error upon launch but that's been happening to me since Unity 5.3 and I've never been able to resolve it (despite many hours effort), not has it seemed to actually effect anything with the different projects be them personal or work related. 
5) There was one instance of GUI layout errors when re-opening a project when the PlayFab extensions was left open and docked with the console panel - this also caused the entire panel to not render (including tabs) had to close and re-open it. 

Current project is using the following libraries: Zenject, Real Series Games Promises, Spine (2D Animation), NetJSON, Full Inspector and some custom compiled IL (should be walled off but you never know - just some stuff to make enums as dictionary keys not box and cause heap allocations). No compile issues, project runs in editor. Appears to have installed the Playfab SDK but I haven't tried using it yet. Deleting the SDK makes the editor extension show the "install SDK" button and that seems to work fine, clicking it re-downloads the SDK but then it ends up in the same state as before. 

I will try to repo in a new empty project after work and if so I'll put the project up on github with commits before and after adding the editor extension and post the editor logs.

**Comment by zac-playfab** [comment]
Great let me know. If you still have issues in a new project, then give me your TitleId for your game and I will test directly on your studio / account / title.

-Zac

**Comment by zac-playfab** [comment]
I just released build 0.0.993. Can you give that version a try and let me know how that goes?

-Thanks,
Zac

**Comment by PpHammer** [comment]
Hi!

I have the exact same issue. 

Win 7 64 bit 
Unity 5.5.0f3
Imported the package in an existing project.
First time install.

Any ideas how to fix this?

Thanks,
Pieter
