### ISSUE TITLE
Issue when upgrading to version > .993

### ISSUE THREAD

**Issue by zac-playfab** [PlayFab/UnityEditorExtensions#57]
We are still in the middle of our beta test. That being said we are experimenting with how we can trigger automated updates from within the Unity IDE.

We caused an issue when upgrading to the latest version, indicated by this error message:

> Assets/PlayFabEditorExtensions/Editor/Scripts/Components/SubMenuComponent.cs(112,18): error CS0101: The namespace `PlayFab.Editor' already contains a definition for`MenuItemContainer'

**Comment by zac-playfab** [comment]
**This can be manually resolved by deleting the MenuComponent.cs file.**

This occurs due to renaming the file. We were hoping the unity package installer would have been smarter about how to handle the upgrade. That being said, we will be looking at other ways to provide EdEx updates.

**Comment by pgilmorepf** [comment]
A lot of these PlayFab.Editor namespace issues have been resolved.
