### ISSUE TITLE
Moving the root folder breaks the tool

### ISSUE THREAD

**Issue by Indiefreaks** [PlayFab/UnityEditorExtensions#58]
I just downloaded the tool and since I organize my projects using a "Plugins" directory where I put every script based tool that I get from the asset store, I tried to place this one alongside the others in a new project.

The tool window gets blank and a lot of ArgumentException raise in the Console on line 106 of the Helper class.

I would like to be able to centralize this tool as well as the resulting PlayFabSDK download in the same location different than root. Could you check why this isn't working? Thanks.

**Comment by pgilmorepf** [comment]
"Plugins" is a reserved folder name in Untiy, which has specific meaning.  Many Unity libraries will not work properly when put into the "Plugins" directory.
https://docs.unity3d.com/Manual/SpecialFolders.html

BUT, I also notice that if we rename PlayFabEditorExtensions, the PlayFab panel no longer behaves correctly.

We will look into the folder renaming and try to make that possible.  However, we will NOT support being renamed or moved into the "Plugins" folder.

**Comment by Indiefreaks** [comment]
I do know the Plugins special folder behavior and that is actually one of the reasons I like to put addons into this folder: they just don't get compiled each time you make a change on your own game scripts which when you start getting quite a big project in size can save you a lot of time in productivity ;)

Now, I do also understand that you don't want to put it there for any good reason you may have. I just would have liked to understand why and not only getting a simple rejection. :)

**Comment by victor-kallai** [comment]
+1 for adding the option the change the tool's default path to Plugin as well as PlayFabSDK's install path.

Reasons for doing so:

- Unity does not recompile the Plugin folder for every change [as Indiefreaks suggested]
- better folder management [personal opinion]
- ability to set the Plugins folder as an svn external/git submodule which you can share between projects

**Comment by Indiefreaks** [comment]
@victor-kallai Could you share the tweek you made so that it works? ;) thx

**Comment by victor-kallai** [comment]
@Indiefreaks  Add these changes to PlayFabEditorHelper.cs:

`
public static string EDEX_ROOT = Application.dataPath + "/Plugins/PlayFabEditorExtensions/Editor";
public static string SDK_DOWNLOAD_PATH = "/Plugins/Resources/PlayFabUnitySdk.unitypackage";
public static string EDEX_UPGRADE_PATH = "/Plugins/Resources/PlayFabUnityEditorExtensions.unitypackage";
public static string EDEX_PACKAGES_PATH = "/Plugins/Resources/MostRecentPackage.unitypackage";
public static string DEFAULT_SDK_LOCATION = "Assets/Plugins/PlayFabSdk";
`

Cheers!

**Comment by Indiefreaks** [comment]
Thx
