### ISSUE TITLE
PlayFab tab re-appears and takes focus on recompile

### ISSUE THREAD

**Issue by rafael-at-jags** [PlayFab/UnityEditorExtensions#61]
Whenever Unity recompiles, the PlayFab tab will re-appear and take focus even after saving.

**Comment by victor-kallai** [comment]
Comment or delete line 77 from PlayFabEditor.cs with the [InitializeOnLoad] attribute.

**Comment by rafael-at-jags** [comment]
Thank you, that fixed the issue.
