### ISSUE TITLE
Checking "Enable Server API / Enable Admin API" doesn't do anything. 

### ISSUE THREAD

**Issue by rafael-at-jags** [PlayFab/UnityEditorExtensions#62]
Even after checking the two options above, I don't have access to the PlayFab.ServerAPI class. The code is still inaccessible and going to Play Settings reveals no precompiler directives have been set.

**Comment by pgilmorepf** [comment]
I need more information about this bug.
Which OS are you using?  Which version of Unity are you using?  What version of the PlayFab SDK do you have installed.

With EdEx in beta, we don't display an independent EdEx version, so I'll also ask you to update to the latest build of Editor Extensions and try again.

**Comment by rafael-at-jags** [comment]
Hi,

The problem is fixed. I think it was a problem with Unity not telling VS to reload the solution.
