### ISSUE TITLE
Unity editor extensions focus

### ISSUE THREAD

**Issue by JohnTube** [PlayFab/UnityEditorExtensions#63]
forwarding issue posted on forum ICYMI:
PlayFab editor extension window is constantly grabbing focus - even from background.
Issue happens on Unity 5.3.3f1.
[link, report on Unity 5.5.2p4](https://community.playfab.com/questions/8859/unity-editor-extensions-focus.html)

**Comment by victor-kallai** [comment]
This is a duplicate of the closed issue #61 
Solution: Comment or delete line 77 from PlayFabEditor.cs with the [InitializeOnLoad] attribute.

**Comment by pgilmorepf** [comment]
We just fixed this issue... again.
It's on the latest master branch.
