### ISSUE TITLE
Cannot paste data into TitleData - or any keyboard shortcuts (like select all)

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/UnityEditorExtensions#66]
* CTRL+V does not paste
* CTRL+A does not select all
* ...etc ;)

This is a bit unfortunate for updating something that may be long or sensitive.

**Comment by pgilmorepf** [comment]
I'll look into this.
I'm not sure if we can do anything about it, since we're just using the basic Unity editor panel widgets.
If they don't support it, then we can't support it.

But I'll check before I reject the bug.

**Comment by pgilmorepf** [comment]
Fixed:
https://github.com/PlayFab/UnityEditorExtensions/commit/9de0ebbb5f15c1bcc9db05157cc1baff061322d2

Thanks for the bug report.
This won't be in the "versioned" branch until the next release, which I expect is 2-3 weeks out.
