### ISSUE TITLE
Can no longer upgrade from inside Unity

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/UnityEditorExtensions#67]
Worked with the old 5.5 extensions, but 5.6 extensions doesn't - the button is seemingly disabled:

![image](https://cloud.githubusercontent.com/assets/8840024/25189899/3470483e-255d-11e7-9566-31b2c951a966.png)

**Comment by dylanh724** [comment]
The button randomly came about after a Unity restart, however, I had an error that I cannot recall (cannot move file from x to y) and it broke everything. I had to rollback from a backup :/

**Comment by dylanh724** [comment]
Manually installing the latest SDK restored things back to normal and editor extensions reappeared, although a bit buggy: My publisher was _OVERRIDE_. There is another issue that I will make a new ticket for.

**Comment by pgilmorepf** [comment]
I have just verified that I can update my UnitySdk version with the latest PfEdEx.
I remember we had an issue with this a while back, but we fixed it.
Sorry, I can't remember the checkin, and looking at the history doesn't really trigger it for me.
