### ISSUE TITLE
Cloud script import will not work

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/UnityEditorExtensions#68]
Pictures:

![image](https://cloud.githubusercontent.com/assets/8840024/25211958/804e702a-25ba-11e7-8b05-8c04503c52a1.png)

![image](https://cloud.githubusercontent.com/assets/8840024/25211977/8839bb3c-25ba-11e7-8a8e-e20e825a19a8.png)

![image](https://cloud.githubusercontent.com/assets/8840024/25211985/939584f2-25ba-11e7-94e3-6fb6f17e9adb.png)

**Comment by pgilmorepf** [comment]
Haven't forgotten this.  Working on the Push Notifications plugin atm.

**Comment by pgilmorepf** [comment]
I've finally taken a look at this.  Sorry for the delay.
It will work in the next release.
