### ISSUE TITLE
NullReferenceException when loading UI style

### ISSUE THREAD

**Issue by ttg-andreas** [PlayFab/UnityEditorExtensions#70]
If the path for the Unity project has the name "Assets" in it some place else than the "Assets" folder inside the Unity project, then a NullReferenceException happens when loading the UI style for the Playfab Editor.

Steps to reproduce:
1) Create a new Unity project and name it "Import Assets"
2) Open up the Unity project.
3) Import the "PlayFabEditorExtensions.unitypackage"
4) NullReferenceException in PlayFabEditor.cs:150

How to fix:
In PlayFabEditorHelper.cs:121 - change from using IndexOf, to LastIndexOf. ie:

var loadPath = eachPath.Substring(eachPath.LastIndexOf("Assets/"));

This will find the correct substring for using when loading the asset.

**Comment by pgilmorepf** [comment]
I actually LOL'ed. Thanks for the bug report. I'll fix it right away.

**Comment by pgilmorepf** [comment]
Here you go:
https://github.com/PlayFab/UnityEditorExtensions/commit/10d796dab03f5cb13981f40b90f65de889f5d112
