### ISSUE TITLE
WsaReflectionExtensions.GetTypeInfo() conflicts with .NET's

### ISSUE THREAD

**Issue by angularsen** [PlayFab/UnityEditorExtensions#73]
After installing PlayFab I'm getting tons of conflicts in [MessagePack for Unity](https://github.com/neuecc/MessagePack-CSharp) trying to use [GetTypeInfo()](https://msdn.microsoft.com/en-us/library/system.reflection.ireflectabletype.gettypeinfo(v=vs.110).aspx).

This seems to due to `WsaReflectionExtensions.GetTypeInfo()` and since it is not declared in a namespace it seems to take precendece.

I think wrapping it in a Playfab namespace would prevent this conflict.

**Comment by angularsen** [comment]
Yup, confirmed that this diff is all that is required:
```diff
diff --git a/Assets/PlayFabSdk/Shared/Internal/wsaReflectionExtensions.cs b/Assets/PlayFabSdk/Shared/Internal/wsaReflectionExtensions.cs
index 3e6acfd..2b3af85 100644
--- a/Assets/PlayFabSdk/Shared/Internal/wsaReflectionExtensions.cs
+++ b/Assets/PlayFabSdk/Shared/Internal/wsaReflectionExtensions.cs
@@ -7,6 +7,7 @@
 using System.Reflection;
 using System.Text;

+namespace PlayFab {
 public static class WsaReflectionExtensions
 {
 #if !NETFX_CORE
@@ -61,3 +62,4 @@ public static IEnumerable<TypeInfo> GetTypes(this Assembly assembly)
     }
 #endif
 }
+}
```

**Comment by MarcoWilliamsPF** [comment]
thanks!  We'll get this updated.

**Comment by pgilmorepf** [comment]
https://github.com/PlayFab/SDKGenerator/pull/153
Should be comitted soon.

**Comment by pgilmorepf** [comment]
Committed, should be in the next release.
