### ISSUE TITLE
PlayFab Editor Extensions window always opens itself.

### ISSUE THREAD

**Issue by AntonyBlackett** [PlayFab/UnityEditorExtensions#76]
The editor extensions window opens itself when I open unity or when unity editor scripts are compiled.

It also says there is no sdk installed, so this might be related to the other issue that has been reported here: https://github.com/PlayFab/UnityEditorExtensions/issues/74

Unity version 2018.1.2f

As a result I've uninstalled the extension.

**Comment by pgilmorepf** [comment]
I'm testing a new resolution to this issue.
Please give this a try:
https://github.com/PlayFab/UnityEditorExtensions/blob/pgilmore/EditorPrefsToSO/Packages/PlayFabEditorExtensions.unitypackage

It's a pre-release of a possible fix.
Please download package and install manually, and respond with any feedback.

**Comment by pgilmorepf** [comment]
All indications are that this is fixed in master. It's already in the asset package here:
https://github.com/PlayFab/UnityEditorExtensions/blob/master/Packages/PlayFabEditorExtensions.unitypackage
And will be in the versioned branch in the next release.
