### ISSUE TITLE
Warnings about usage of PlayFabSettings.PlayFabShared which is marked as obsolete

### ISSUE THREAD

**Issue by nlebedenco** [PlayFab/UnityEditorExtensions#85]
Editor shows several warnings about usage of PlayFabSettings.PlayFabShared which is marked to be removed after Mar 1, 2017. (no, seriously!?)

**Comment by nlebedenco** [comment]
After looking closer it seems I should have created this issue for the PlayFabSDK, I guess? It only happens for builds with both server api and playstream api enabled. Root cause is PlayFabSettings.ProductionEnvironmentPlayStreamUrl which is used by PlayFabStreamAPI.Start()

**Comment by pgilmorepf** [comment]
That's a really good catch, thanks.
I'll investigate.
(And yeah, we put a date on there way back when, but we waited much longer to avoid breaking people)

**Comment by pgilmorepf** [comment]
This issue should be resolved in the next build.
Thanks for your submission.
