### ISSUE TITLE
SDK & extension explodes if moved into non-root level path

### ISSUE THREAD

**Issue by gekidoslair** [PlayFab/UnityEditorExtensions#88]
Whole thing seems to be hard-coded to require being placed at the root folder of a Unity project. 

Repro: move PlayFabEditorExtensions and PlayFabSdk folders into a subfolder (say called 'packages') - boom

**Comment by pgilmorepf** [comment]
Yes, we're aware of this.
The SDK should be movable, but the extensions are not.
I'll file a bug for this issue on our internal systems, but I don't think it'll be resolved right away.

**Comment by brzGatsu** [comment]
This issue is already quite old, is there an ETA for the fix? I like to keep my project root clean. I generally put all external stuff into the Plugins folder for increased compilation time.

**Comment by pgilmorepf** [comment]
We accept that this is a reasonable feature request, but we don't have immediate plans to address it.
I will add your "+1" to the backlog item.

**Comment by toddbellMSFT** [comment]
This should be fixed in the latest version of the editor. 

There's a dangling issue where we may generate a file in the old path, but you shouldn't see any more errors/explosions.
