### ISSUE TITLE
Editor Extensions compile error with UnityEditorExtensions V2.54

### ISSUE THREAD

**Issue by Myfreedom614** [PlayFab/UnityEditorExtensions#92]
Community LINK: https://community.playfab.com/questions/24559/editor-extensions-compile-error-with-older-2x-sdk.html

Exception in Unity:
> Assets/PlayFabEditorExtensions/Editor/Scripts/Panels/PlayFabEditorPackages.cs(8,42): error CS0118: `PlayFab.Editor' is a `namespace' but a `type' was expected

Code line: https://github.com/PlayFab/UnityEditorExtensions/blob/master/Source/Assets/PlayFabEditorExtensions/Editor/Scripts/Panels/PlayFabEditorPackages.cs#L8

Should be renamed to `PlayFab.Editor`

**Comment by toddbellMSFT** [comment]
Fixed with commit https://github.com/PlayFab/UnityEditorExtensions/commit/5ea9d2a6dab7bddbf7e44785bd7573717e6fb356
